config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"
  resources :kittens
  namespace 'api' do
    resources :kittens, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord

  def as_json(options = {})
    super(only: [:id, :name, :cuteness, :softness])
  end
end

app/controllers/api/kittens_controller.rb
module API
  class KittensController < ApplicationController
    def index
      @kittens = Kitten.all
      render json: @kittens
    end

    def show
      @kitten = Kitten.find(params[:id])
      render json: @kitten
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :destroy]

  def index
    @kittens = Kitten.all
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten adopted!"
      redirect_to root_path
    else
      flash.now[:info] = "Something went wrong"
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
  end

  def destroy
    @kitten.destroy
    flash[:info] = "The kitten is given away!"
    redirect_to root_path
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

    def set_kitten
      @kitten = Kitten.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<% provide(:btn_title, "Change info!") %>

<h1>Change <%= @kitten.name %> info</h1>

<%= render "shared/kitten-form" %>

app/views/kittens/index.html.erb
<h1>All our cute kittens!</h1>

<p><%= link_to "Adopt new kitten", new_kitten_path %></p>
<% @kittens.each do |kitten| %>
  <h2><%= kitten.name %></h2>
  <p><%= kitten.cuteness %></p>
  <p><%= kitten.softness %></p>
  <p><span><%= link_to "Detail", kitten_path(kitten) %></span> |
  <span><%= link_to "Change", edit_kitten_path(kitten) %></span> |
  <span><%= link_to "Give away", kitten_path(kitten),
                                method: :delete,
                                data: { confirm: "You sure?"} %></span></p>
<% end %>

app/views/kittens/new.html.erb
<% provide(:btn_title, "Adopt this kitten!") %>

<h1>Adopt new kitten</h1>

<%= render "shared/kitten-form" %>

app/views/kittens/show.html.erb
<h1>Infomation of <%= @kitten.name %></h1>
<p><%= @kitten.cuteness %></p>
<p><%= @kitten.softness %></p>
<p><span><%= link_to "Detail", kitten_path(@kitten) %></span> |
<span><%= link_to "Change", edit_kitten_path(@kitten) %></span> |
<span><%= link_to "Give away", kitten_path(@kitten),
                              method: :delete,
                              data: { confirm: "You sure?"} %></span></p>
<p><%= link_to "Back", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% flash.each do |type, msg| %>
        <ul>
          <li>
            <%= msg %>
          </li>
        </ul>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_kitten-form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.select :age, options_for_select([[1,1],[2,2],[3,3],[4,4]]) %>

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>

  <%= f.label :softness %>
  <%= f.text_field :softness %>
  <br>
  <%= f.submit yield(:btn_title) %>
<% end %>